---
# tasks file for auditd
- name: install auditd service
  apt: 
    pkg:
      - auditd 
    state: present

# See: https://man7.org/linux/man-pages/man5/auditd.conf.5.html
- name: edit auditd log format
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^log_format\s*=\s*RAW.*$'
    line: 'log_format = ENRICHED'
    backup: yes

- name: create auditd.rules
  copy:
    src: ./auditd.rules/
    dest: /etc/audit/rules.d/
  notify: restart auditd
