- name: Create/Update datasources file (provisioning)
  become: true
  copy:
    dest: "{{install_dir}}/grafana/provisioning/datasources/ds.yml"
    content: |
      apiVersion: 1
      deleteDatasources: []
      datasources:
      {{ grafana_datasources | to_nice_yaml }}
  notify: restart nginx-grafana-compose