---
- name: restart loki
  become: true
  systemd:
    daemon_reload: true
    name: "{{service_name}}"
    state: restarted

- name: reload loki
  become: true
  systemd:
    name: "{{service_name}}"
    state: reloaded