---
# tasks file for promtail-compose
- name: secure dir
  file:
    path: "{{install_dir}}"
    state: directory
    owner: "{{docker_username}}"
    group: docker
    mode: 0700

- name: copy templates
  template:
    src: "{{item}}"
    dest: "{{install_dir}}/"
  loop:
    - tz.env
    - docker-compose.yml
    - promtail-config.yml
  notify: restart promtail-compose

- name: create service file
  template:
    src: promtail.service
    dest: /etc/systemd/system/{{service_name}}.service

- name: start service
  systemd: 
    name: "{{service_name}}"
    state: started 
    enabled: yes 
    daemon_reload: yes
  
