---
- name: restart prometheus
  systemd:
    daemon_reload: true
    name: "{{service_name}}"
    state: restarted

- name: reload prometheus
  systemd:
    name: "{{service_name}}"
    state: reloaded